### ISSUE TITLE
Stimuli size

### ISSUE THREAD

**Issue by nataliasc** [104H/dyadicdecisionmaking#11]
For a direct replication of the de Gee paper, stimuli should be of radius 4.8 ± 1.8 degrees of visual angle ([de Gee et al. 2014](https://www.pnas.org/content/early/2014/01/15/1317557111)). PsychoPy's [monitorunittools](https://www.psychopy.org/api/tools/monitorunittools.html) can be of use here.

**Comment by 104H** [comment]
What is the unit of 4.8?

**Comment by nataliasc** [comment]
Degrees of visual angle, so `deg` in [PsychoPy](https://www.psychopy.org/general/units.html#degrees-of-visual-angle)
