### ISSUE TITLE
Stimuli display duration

### ISSUE THREAD

**Issue by nataliasc** [104H/dyadicdecisionmaking#12]
`core.wait()` is imprecise, and the best way to time the duration of the stimuli staying on screen is by using frame refresh periods (cf. [Bridges et al. 2020](https://doi.org/10.7717/peerj.9414)). Once we know the exact monitor model we'll be using for experiment, we can convert seconds to frames.
The benQ monitor specification can be found [here](https://www.displayspecifications.com/en/model-response-time/0a759b4).
E.g. for a refresh rate of 60 Hz (16.7 ms per frame), if we want a stimulus to stay on screen for 300 ms, we would specify 300 ms/16.7 = 18 frames; frames have to be rounded to nearest whole number.
Example of displaying a stimulus for 18 frames:

```
for frame in range(18):
    stimulus.draw()
    win.flip()
```
[Older reference on timing](https://www.djmannion.net/psych_programming/vision/temporal/temporal.html)

PsychoPy, however, does not have a setting for sounds to be timed by frames.

**Comment by 104H** [comment]
Right now the right chamber has one Dell and one BenQ. Will need two identical monitors when we collect data from subjects.

**Comment by 104H** [comment]
We need to implement our own wait function which takes an an argument the number of seconds of wait needed.

`
def wait (seconds, stimulusfunction):
    frames = (1000 / framerate) * seconds
    for frame in range(frames):
        stimulusfunction()
        win.flip()
`

The arguments to the function will be the seconds and the function object (not call).

**Comment by nataliasc** [comment]
More on timing here <https://www.psychopy.org/coder/codeStimuli.html>

**Comment by 104H** [comment]
Courtesy of Faraz

Refresh rate is 60Hz
https://dyadicdecisionmaking.slack.com/files/U01NPP2M7EY/F020MM138DQ/specification_of_xl2420t__monitor_screen.docx
