### ISSUE TITLE
Stimuli display (dynamic)

### ISSUE THREAD

**Issue by frbosse** [104H/dyadicdecisionmaking#14]
The luminance across all pixels should deviate from the mean luminance symmetrically in both directions and be refreshed on every frame.

**Comment by nataliasc** [comment]
So probably set `mask` for `RadialStim` to something other than `'none'` as it is *"a 1D array specifying the luminance profile extending outwards from the center of the stimulus"* (PsychoPy manual), and if it has to flicker on every frame, use `setOpacity` as described here? <https://discourse.psychopy.org/t/blinking-texts-and-images/6332/7>

**Comment by nataliasc** [comment]
I've added my idea (using `NoiseStim`) here <https://github.com/104H/dyadicdecisionmaking/blob/main/experiment_files/dynamic-noise.py>

**Comment by 104H** [comment]
ran the file. looks good.
does it pass our theoretical experimental requirements? is the code ready for integration?

**Comment by nataliasc** [comment]
I was hoping for the meeting today to resolve the questions about what the stimuli looked like in the original study.

For example, there is a mention of "binary noise pattern of 5% contrast", but if I set the contrast for noise as low as 5%, it looks nothing like the figures in the paper.

Re integration, Integrating this into the main experiment should be easy.

**Comment by 104H** [comment]
How about this: we can integrate the code and correct the parameters when we have them. The issue remains open.
Or, we could let the matter rest for now.

**Comment by nataliasc** [comment]
Yeah, I can add this to the main experiment.
