### ISSUE TITLE
Signal presence on 50% of all trials in a block

### ISSUE THREAD

**Issue by nataliasc** [104H/dyadicdecisionmaking#15]
According to the de Gee paper, in each block of 80 trials, signal has to be present on 50% of trials in that block

> Signal presence was randomly selected on each trial, under the constraint that it would occur on 50% of the trials within each block of 80 trials.

_Originally posted by @nataliasc in https://github.com/104H/dyadicdecisionmaking/issues/7#issuecomment-830627662_

**Comment by zora-no** [comment]
To be able to do this with the trial handler we need to create a spreadsheet with 80 rows, 40 with signal, 40 without, and read that into the trial handler.

**Comment by zora-no** [comment]
are there any objections against this? @frbosse @nataliasc @104H

**Comment by frbosse** [comment]
First I want to point out that this constraint needs to be handled with care since we have a **dyadic** setup. I think we want to avoid that in one block participant 1 has a signal present in all of his do-trials and participant 2 in none of his do-trials (in worst case). If so we have to find a more sophisticated solution.

**Comment by zora-no** [comment]
But wasn't it decided that we would choose the acting participant randomly on each trial, despite the worst case you mentioned? That's why we will end up with a varying number of blocks, depending on how that randomization goes.

**Comment by zora-no** [comment]
Conclusion:
**Signal presence on 50% of trials
On each trial, the participants are assigned to act/ observe randomly**

**Comment by ArtuDitu** [comment]
I agree with the conclusion

**Comment by 104H** [comment]
I think this is already taken care of in the `trialHandler`

>  ‘random’ will result in a shuffle of the conditions on each repeat, but all conditions occur once before the second repeat etc. ‘fullRandom’ fully randomises the trials across repeats as well, which means you could potentially run all trials of one condition before any trial of another.

[Trial Handler Docs](https://www.psychopy.org/api/data.html#psychopy.data.TrialHandler)

**Comment by 104H** [comment]
I think issue this issue needs to be combined with #7 
The trial handler needs to be given a list of 4:

1. sone acting, stwo observing, signal present
2. sone acting, stwo observing, signal absent
3. sone observing, stwo acting, signal present
4. sone observing, stwo acting, signal absent

using the `fullRandom` setting of the trial handler, we can generate fully random conditions of the 4 possibilities

the changes to the state of the subject will have to be reflected from here

**Comment by zora-no** [comment]
> I think this is already taken care of in the `trialHandler`
> 
> > ‘random’ will result in a shuffle of the conditions on each repeat, but all conditions occur once before the second repeat etc. ‘fullRandom’ fully randomises the trials across repeats as well, which means you could potentially run all trials of one condition before any trial of another.
> 
> [Trial Handler Docs](https://www.psychopy.org/api/data.html#psychopy.data.TrialHandler)

But then we lose the "signal on 50% of trials" constraint. That's why the idea was to just feed a list of 80 trials with just signal/ no signal to the trial handler an on each trial randomly decide who acts/ observes.
