### ISSUE TITLE
Handling the start of the experiment

### ISSUE THREAD

**Issue by frbosse** [104H/dyadicdecisionmaking#16]
As we are getting closer completing the experiment I wonder how we will manage the instruction phase in the beginning of the experiment. Right now we decide when the experiment is to start (by pressing space). But shouldn't the participants do this on their own? Such that the experiment starts if both of the participants have thoroughly read the instructions and confirm this by pressing a button on their button-box?

**Comment by zora-no** [comment]
We would need to implement the same for the breaks, right?

**Comment by frbosse** [comment]
Yes, there we have the same "problem".

**Comment by 104H** [comment]
Raised a new issue for starting breaks.

For starting the experiment, is it enough to get a verbal acknowledgement from the subjects and press spacebar on the keyboard?

**Comment by 104H** [comment]
I raised an issue for starting the break and developed a mechanism to get acknowledgements on having read the instructions from both subjects to start the experiment.

If there is anything else that needs to be addressed, please reopen the issue or open another one.
