### ISSUE TITLE
Prepare Correct Instruction

### ISSUE THREAD

**Issue by 104H** [104H/dyadicdecisionmaking#20]
Need correct instruction screen for the
1. start
2. inter-block break
3. inter-block mandatory break

**Comment by zora-no** [comment]
**Currently**

**1. Welcome Screen**
to be done

**2. Instructions**
Your task is to indicate if you see a vertical grating or not.
    1. At the start of each trial, a red dot is shown in the middle of the screen.
    2. When you hear a beep, you may press one of the buttons to indicate if you saw a vertical grating or not.
    3. Press the left key for 'yes' and the right key for 'no'.
    4. After a short break, the procedure will be repeated from step 1.
    5. After 80 trials, you will have a break.
    6. After the break, press the spacebar when ready to continue.
    7. There will be a total of 6 blocks.
    Press yes when ready.

**3. self-paced break**
Enjoy your break. Press yes when you're ready to resume.

**4. mandatory break**
Enjoy your break. The experimenter will resume the experiment."

**5. end screen**
"Thank you for your time."

**Comment by zora-no** [comment]
Implemented the following for now (will discuss changes in the next meeting):


**Welcome Screen**
Welcome to our experiment!
Your task is to indicate whether you see a vertical grating or not.
If you have any questions after reading the instructions on the next screen, please feel free to ask the experimenter.

Press yes to continue

**Instructions 1: before practice**
Please read the instructions carefully.
1. First, you will have a few practice trials to see how the experiment works.
2. You will do the task together with your partner.
3. At the start of each trial, a red dot is shown in the middle of the screen, surrounded by a circular pattern that looks similar to white noise.
4. When you hear a beep, it’s your turn to indicate whether you saw a vertical grating on top of the noise.
5. Press the left key for 'yes' and the right key for 'no'.
6. It’s very important that you respond as fast as possible! You only have a limited amount of time for your response.
7. If you don’t hear a beep, it’s the other person’s turn to respond. You will both see the grating (or not) and you will also see their response on your screen. 

Press yes to continue

**Instructions 2: before titration**
Please read the instructions carefully.
1. Now we will determine your individual threshold for recognizing the vertical grating.
2. The procedure is the same as before: when you hear a beep, press the left key if you saw a grating, and the right key if you didn’t.
3. The visibility of the grating will be adjusted throughout the trials.

Press yes to continue

**Instructions 3: before experiment**
Now you’re ready to start the experiment. Please remember:
1. When you hear a beep it’s your turn. If you don’t hear a beep, you will see your partner’s response.
2. Press the left key for 'yes' and the right key for 'no'.
3. Please respond as fast as possible!
4. Once you finished one block, you’ll be asked if you’re ready for the next block.
5. After every second block, you will have a break.
6. There will be a total of 12 blocks.

Press yes when you’re ready to start the experiment

**self-paced break**
Are you ready for the next block? 

Press yes when you're ready to resume

**mandatory break**
Enjoy your break. The experimenter will resume the experiment.

**end screen**
Thank you for your time!

**Comment by nataliasc** [comment]
In today's meeting we mentioned adding instructions to use the index and middle fingers of the right hand, counterbalance the mappings across participants like in the de Gee study, and also adding a point about accuracy (e.g. "try to respond as fast and as accurate as possible").
