### ISSUE TITLE
Data Pipeline column names

### ISSUE THREAD

**Issue by 104H** [104H/dyadicdecisionmaking#34]
The column names in the data pipeline are inconsistent with the column names in the data file. The pipeline is also designed on the assumption that both the subjects are acting. Need to review and introduce relevant changes.

**Comment by 104H** [comment]
@frbosse Does it make more sense to tailor the variables to as they are in [the Urai code](https://github.com/anne-urai/2019_Urai_choice-history-ddm/blob/master/simulations/1_ddm_rts.py) instead, because that is our ultimate objective?

**Comment by frbosse** [comment]
I am currently working with Saurabh on a solution. We both agreed that no changes in the experiment code are needed, we will tailor the data during a preprocessing step.

**Comment by 104H** [comment]
A better pipeline was built and pushed and we decided to not pursue any further work in the old one.
