### ISSUE TITLE
Take subject ID input

### ISSUE THREAD

**Issue by 104H** [104H/dyadicdecisionmaking#4]
There is no mechanism to input a subject ID at the start of the experiment.
This can either be done with a dialog box in the beginning or using command line arguments from the terminal.

**Comment by zora-no** [comment]
How about doing something like this: https://discourse.psychopy.org/t/participant-input-using-code/10878 ?

**Comment by frbosse** [comment]
I think I will go with a command line argument first, we can enhance this later if we want to.

**Comment by nataliasc** [comment]
Perhaps it makes sense to only enter dyad number, and always have e.g. `1` and `2` as participant IDs?

**Comment by frbosse** [comment]
Now, that I had a look at the output-file it makes sense to handle it like you said. I will change it.
