### ISSUE TITLE
Blend mode `add` not possible with Pyglet

### ISSUE THREAD

**Issue by 104H** [104H/dyadicdecisionmaking#40]
The following warning is displayed since the introduction of `blendmode='add'`

`4.2160 	WARNING 	Pyglet text does not honor the Window setting `blendMode='add'` so 'avg' will be used for the text (but objects drawn after can be added)`

Blend mode add is necessary for the experiment, so this needs resolution.

**Comment by nataliasc** [comment]
This is for text stimuli only — the instructions — so I think we can ignore it

**Comment by zora-no** [comment]
source: https://www.psychopy.org/_modules/psychopy/visual/text.html

We also use `visual.TextStim` for the feedback (no, yes, noresponse)

**Comment by zora-no** [comment]
source: https://www.psychopy.org/_modules/psychopy/visual/text.html

We also use `visual.TextStim` for the feedback (no, yes, noresponse) but this is irrelevant.
```
        if win.blendMode=='add':
            logging.warning("Pyglet text does not honor the Window setting "
                            "`blendMode='add'` so 'avg' will be used for the "
                            "text (but objects drawn after can be added)")
```
