### ISSUE TITLE
Based on what criterion do we switch between the action and observation states

### ISSUE THREAD

**Issue by 104H** [104H/dyadicdecisionmaking#7]
How is the decision of changing the action state of a subject made?
Do we sample randomly from a distribution? Do we account for how many times a subject and their partner has been in a condition?

**Comment by frbosse** [comment]
As discussed yesterday for each trial we randomly decide who is doing the do-trial and who is doing the observe-trial. Given this we need a counter of how many trials each participant has done, because we need at least 480 trials each.

**Comment by 104H** [comment]
So the number of trials performed can be an attribute of the subject class.
As for the random decision, I think we can randomly sample from a uniform distribution between 0 and 1 and round off the value, and 1 and 0 can represent the turn of the subject.

**Comment by 104H** [comment]
There is a possibility to use the Experiment and/or Block handler. I think it has a `random` or `fully random` setting, but I'm not sure if this accounts for a minimum number of trials per subject. The docs need to be read on this.

**Comment by nataliasc** [comment]
Based off [this thread](https://discourse.psychopy.org/t/how-to-ensure-randomised-sound-is-50-50-across-trials/11043/3), I'd suggest
```
condition = ['act', 'obs'] * 480
shuffle(condition)
```

**Comment by 104H** [comment]
this can lead to both of them being in the acting condition.

**Comment by 104H** [comment]
I like the approach but I don't know about the `shuffle` function's implementation
How is this better than, 
` trials = np.round( np.rand.uniform(0, 1, 480) )`
in english, this means, sample 480 random numbers from a uniform distribution and round them off.
0 and 1 represent act and obs, respectively

**Comment by nataliasc** [comment]
In the `shuffle` approach, you start with exactly 480 "do" trials and exactly 480 "observe" trials (it just goes "act, observe, act, observe"), then `shuffle` shuffles their order so that they are ordered randomly. `numpy.random.uniform` will not return exactly 480 ones and exactly 480 zeroes.

**Comment by nataliasc** [comment]
In the de Gee paper, they did this for signal presence: "Signal presence was randomly selected on each trial, under the constraint that it would occur on 50% of the trials within each block of 80 trials."

**Comment by 104H** [comment]
> In the `shuffle` approach, you start with exactly 480 "do" trials and exactly 480 "observe" trials (it just goes "act, observe, act, observe"), then `shuffle` shuffles their order so that they are ordered randomly. `numpy.random.uniform` will not return exactly 480 ones and exactly 480 zeroes.

I think you are right, but the use of shuffle is not a criterion on its own, we need to see how it is implemented and how it shuffles the list.



> In the de Gee paper, they did this for signal presence: "Signal presence was randomly selected on each trial, under the constraint that it would occur on 50% of the trials within each block of 80 trials."

This deserves a separate issue. Please open and post there.

**Comment by nataliasc** [comment]
It randomises the order of items in the list <https://www.w3schools.com/python/ref_random_shuffle.asp>

<https://www.w3schools.com/python/ref_random_random.asp>

**Comment by zora-no** [comment]
To be able to do this with the trial handler we need to create a spreadsheet with 80 rows, 40 with signal, 40 without, and read that into the trial handler.

**Comment by 104H** [comment]
Numpy shuffle uses a Fischer-Yates shuffle. We can now qualify our design

[Source](https://softwareengineering.stackexchange.com/questions/215737/how-python-random-shuffle-works)
